RegiHuer/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

accesibilidad/urls.py
from django.urls import path
from . import views

app_name = 'accesibilidad'
urlpatterns= [ 
        path('menu_carga_inicial', views.menu_carga_inicial,name='menu_carga_inicial'),
        path('gestion_menu', views.gestion_menu,name='gestion_menu'),
        path('menu_eliminar', views.menu_eliminar,name='menu_eliminar'),
        
]

composeexample/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
]
urlpatterns += [
    path('catalog/', include('catalog.urls')),
]
urlpatterns += [
    path('', RedirectView.as_view(url='/catalog/', permanent=True)),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

home/urls.py
from django.urls import path, include 
from django.conf import settings
from django.conf.urls.static import static
from . import views    
urlpatterns = [
    path('', views.index,name='index'),
    path('registracion', views.registrar,name='registrar'),
    path('validacion', views.mailValidador,name='mailValidador'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accesibilidad/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import Group

# Create your models here.
class Menu(models.Model):
    TIPO = (
        ('P', 'Padre'),
        ('I', 'Intermedio'),
        ('H', 'Hoja'),
    )
    url = models.CharField(max_length=250, blank=True,null=True)
    nombre = models.CharField(max_length=250,unique=True)
    tipo = models.CharField(max_length=1, choices=TIPO)
    menuPadre = models.ForeignKey("self",related_name="subMenu",on_delete=models.CASCADE,blank=True,null=True, )

    # no es el mejor modo de retornar la URL pero es facil de entender :D
    def get_absolute_url(self):
        return "%s" % self.url 
        
    def __unicode__(self):
        return u'%s' % self.nombre

    def __str__(self):
      return f"{self.url} {self.nombre} {self.tipo}"
    

class MenuGroup(models.Model):
    menu = models.ForeignKey(Menu, on_delete=models.CASCADE)
    groups = models.ForeignKey(Group, on_delete=models.CASCADE, null=True)

    def __str__(self):
      return f"{self.menu} {self.groups}"
    
    def get_absolute_url(self):
        """
        Retorna la url para acceder a una instancia particular de un autor.
        """
        return reverse('author-detail', args=[str(self.id)])

accesibilidad/views.py
from django.shortcuts import render
from django.contrib.auth.models import Group
from .models import MenuGroup, Menu
import csv
# Create your views here.
def gestion_menu(request):
    menu = Menu.objects.all()
    contexto ={"listadoMenu":menu,
               "menu": generarMenu("hola")
    }

    return render(request, "gestion_menu.html",contexto)

def menu_eliminar(request):
    Menu.objects.all().delete()
    menu = Menu.objects.all()
    contexto ={"menu":menu,
    }

    return render(request, "gestion_menu.html",contexto)


def ObtenerMenu(user):
    print(user)
    group =Group.objects.filter(user=user)
    menuUsuario = MenuGroup.objects.filter(groups__in = group, menu__nivel=1)
    #menu = Menu.objects.filter(id__in = menuUsuario.menu_id)
    print(menuUsuario )
    #permisos = MenuGroup.objects.filter(groups= user.groups)
  #  print(permisos)
   # return Menu.objects.all()
    return menuUsuario


def generarTagPrincipalHoja(menu, orden):
    if orden > 1:
      menuTitle = 'menu-title_'+str(orden)
    else:
        menuTitle=''
    me =[]
    tag = [{'tag':'<li>'}]
    me = [tag]
    
    tag = []
    tag.append({'tag':'<a>','href':menu.url, 'class':'menu'})
    me.append(tag)
    
    tag =[]
    tag.append({'tag':'<h2>', 'class':'menu-title '+menuTitle, 'descripcion':menu.nombre})
    me.append(tag)
    
    tag =[]
    tag.append({'tag':'<ul>', 'class':'menu-dropdown', })
    me.append(tag)

    tag =[]
    tag.append({'tag':'</ul>'})
    me.append(tag)
    
    tag =[]
    tag.append({'tag':'</a>'})
    me.append(tag)
    
    tag =[]
    tag.append({'tag':'</li>'})
    me.append(tag)
  
    return me
def generarTagPrincipalPadre(menu,orden):
    if orden > 1:
      menuTitle = 'menu-title_'+str(orden)
    else:
        menuTitle=''
    me =[]
    tag = [{'tag':'<li>'}]
    me = [tag]
    
    tag = []
    tag.append({'tag':'<div>','class':'menu'})
    me.append(tag)
    tag =[]

    tag.append({'tag':'<h2>', 'class':'menu-title '+menuTitle, 'descripcion':menu.nombre})
    me.append(tag)
    tag =[]
    tag.append({'tag':'<ul>', 'class':'menu-dropdown', })
    me.append(tag)
    menuHijos = Menu.objects.filter(menuPadre = menu)
    #print("menu hijo:", menuHijos)
    for mh in menuHijos:
        tag=[]
        if mh.tipo=='H':
            print('tag hijo mh:', mh)
            tag.append({'tag':'<li>'})
            me.append(tag)
 
            tag=[]
            tag.append({'tag':'<a>','href':mh.url, 'class':'menu', 'descripcion':mh.nombre})
            me.append(tag)
        
            tag =[]
            tag.append({'tag':'</a>'})
            me.append(tag)

            tag=[]
            tag.append({'tag':'</li>'})
            me.append(tag)
    tag =[]
    tag.append({'tag':'</ul>'})
    me.append(tag)
    tag =[]
    tag.append({'tag':'</div>'})
    me.append(tag)
    tag =[]
    tag.append({'tag':'</li>'})
    me.append(tag)
  


    return me
def generarMenu(user):
  menu =[]
  menues = Menu.objects.filter( menuPadre__isnull = True )
  orden = 1
  for me in menues:
      if me.tipo=="H":
          menu.extend(generarTagPrincipalHoja(me,orden))
      elif me.tipo == 'P':
          menu.extend(generarTagPrincipalPadre(me,orden))
      if orden == 4:
       orden =1
      else:
        orden +=1
   
  #print(menues)
  #print("menu generado:",menu)
  return menu


def menu_carga_inicial(request):
    template_name = "accesibilidad/migrations/menues.csv"
    model = Menu()
    #Disciplinas.objects.all().delete()
    with open (template_name) as f:
        reader = csv.reader(f )
        for row in reader:
         #  print("row:",row)
           if  not Menu.objects.filter(nombre = row[1]).exists():
               if  Menu.objects.filter(nombre = row[3]).exists():
                 #  print("dentro de Menu Padre:", row[3])
                   menuP = Menu.objects.get(nombre = row[3])
                   model.menuPadre = menuP
                   Menu.objects.create(url = row[0], nombre =row[1] ,tipo = row[2],menuPadre = menuP)
               else:
                   print("No hay de Menu Padre:", row[3])
                   Menu.objects.create(url = row[0], nombre =row[1], tipo = row[2])
    mensaje ="carga con exito"
    contexto ={  
        "mensaje":mensaje , 
        "menu": generarMenu(request.user),
        "listadoMenu": Menu.objects.all(), 
    } 
    return render (request, "gestion_menu.html",contexto)

accesibilidad/templates/gestion_menu.html
{% extends "base_nav.html"%}
{% block title %} Mostrar Menu para Carga Inicial {% endblock %}
{% load static %}
{% block style %} 
    <link rel='stylesheet' href="{% static 'css/huertas.css' %}" type="text/css">
    <script type="text/javascript" src="{% static 'js/cultivos.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.1/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
{% endblock %}
 
{% block body %} 
{% load static %}
<div class="row">
    <div class="alertas">
        {% if messages %}
        {% for message in messages %}
        <div>
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <strong class="text-dark">{{ message }}</strong>
        </div>
        {% endfor %}
        {% endif %}
    </div>
    <div class="datos-cuerpo-cabecera">
    </div>
    <div class="datos-cuerpo-listado">
        <h1>Configuracion de Menu</h1>
    </div>
        <div class="tabla-listar">
            <div class="agregar">
                <a href="{% url 'accesibilidad:menu_eliminar'  %}">
                    <img src="{% static 'img/eliminar.png' %}" alt="eliminar" title="eliminar">
                </a>

                <a href="{% url 'accesibilidad:menu_carga_inicial'  %}">
                    <img src="{% static 'img/agregar.png' %}" alt="cargar" title="cargar">
                </a>
            </div>

            <table id="resultados" class="table">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Menu</th>
                        <th colspan="3">Opciones</th>
                    </tr>
                </thead>
                <tbody id="listCultivos">
                    {% if listadoMenu %}
                    {% for me in listadoMenu%}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{me }}</td>
                        
                        </tr>
                    {% endfor %}
                    {% endif %}
                </tbody>
            </table>
        </div>
    </div>
</div>
<script>
    $(document).ready(__init);
</script>
{% endblock %}  