RegiHuer/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

composeexample/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
]
urlpatterns += [
    path('catalog/', include('catalog.urls')),
]
urlpatterns += [
    path('', RedirectView.as_view(url='/catalog/', permanent=True)),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

configuracion/urls.py
from django.urls import path
from django.urls import include, re_path
from . import views
app_name = 'configuracion'
urlpatterns= [ 
       path('gestion_hortelanos', views.gestion_hortelanos,name='gestion_hortelanos'),
       path('configuracion/consultaPersona/<int:persona_id>/', views.consultaPersona, name='consultaPersona'),
       path('configuracion/registrarHortelano/', views.registrarHortelano),
       path('hortelano_editar/<int:id>/', views.hortelano_editar, name='hortelano_editar'),
       path('hortelano_modificar/', views.hortelano_modificar),
       path('hortelano_eliminar/<int:id>', views.hortelano_eliminar),

       path('gestion_cultivos', views.gestion_cultivos, name = 'gestion_cultivos'),
       path('cultivo_agregar', views.cultivo_agregar, name='cultivo_agregar'),
       path('cultivo_eliminar/<int:id>', views.cultivo_eliminar, name='cultivo_eliminar'),
       path('cultivo_editar/<int:id>', views.cultivo_editar, name='cultivo_editar'),
       re_path(r'^configuracion/cultivo_buscar', views.cultivo_buscar, name ='cultivo_buscar'),


       path('gestion_tierras_cultivo/', views.gestion_tierras_cultivo, name = 'gestion_tierras_cultivo'),
       path('configuracion/tierras_cultivo_agregar/', views.tierras_cultivo_agregar, name='tierras_cultivo_agregar'),
       path('configuracion/tierras_cultivo_eliminar/<int:id>/', views.tierras_cultivo_eliminar, name='tierras_cultivo_eliminar'),
       path('configuracion/tierras_cultivo_editar/<int:id>/', views.tierras_cultivo_editar, name='tierras_cultivo_editar'),

       path('gestion_temperaturas/', views.gestion_temperaturas, name = 'gestion_temperaturas'),
       path('configuracion/temperaturas_agregar/', views.temperaturas_agregar, name='temperaturas_agregar'),
       path('configuracion/temperaturas_eliminar/<int:id>/', views.temperaturas_eliminar, name='temperaturas_eliminar'),
       path('configuracion/temperaturas_editar/<int:id>/', views.temperaturas_editar, name='temperaturas_editar'),

       path('gestion_luz_cultivos/', views.gestion_luz_cultivos, name = 'gestion_luz_cultivos'),
       path('configuracion/luz_cultivos_agregar/', views.luz_cultivos_agregar, name='luz_cultivos_agregar'),
       path('configuracion/luz_cultivos_eliminar/<int:id>/', views.luz_cultivos_eliminar, name='luz_cultivos_eliminar'),
       path('configuracion/luz_cultivos_editar/<int:id>/', views.luz_cultivos_editar, name='luz_cultivos_editar'),

       path('gestion_riego_cultivos/', views.gestion_riego_cultivos, name = 'gestion_riego_cultivos'),
       path('configuracion/riego_cultivos_agregar/', views.riego_cultivos_agregar, name='riego_cultivos_agregar'),
       path('configuracion/riego_cultivos_eliminar/<int:id>/', views.riego_cultivos_eliminar, name='riego_cultivos_eliminar'),
       path('configuracion/riego_cultivos_editar/<int:id>/', views.riego_cultivos_editar, name='riego_cultivos_editar'),

       path('gestion_enfermedades/', views.gestion_enfermedades, name = 'gestion_enfermedades'),
       path('configuracion/enfermedades_agregar/', views.enfermedades_agregar, name='enfermedades_agregar'),
       path('configuracion/enfermedades_eliminar/<int:id>/', views.enfermedades_eliminar, name='enfermedades_eliminar'),
       path('configuracion/enfermedades_editar/<int:id>/', views.enfermedades_editar, name='enfermedades_editar'),

       path('gestion_plagas/', views.gestion_plagas, name = 'gestion_plagas'),
       path('configuracion/plagas_agregar/', views.plagas_agregar, name='plagas_agregar'),
       path('configuracion/plagas_eliminar/<int:id>/', views.plagas_eliminar, name='plagas_eliminar'),
       path('configuracion/plagas_editar/<int:id>/', views.plagas_editar, name='plagas_editar'),

       path('configuracion_carga_inicial', views.configuracion_carga_inicial,name='configuracion_carga_inicial'),
       path('carga_inicial_tierra_cultivo', views.carga_inicial_tierra_cultivo,name='carga_inicial_tierra_cultivo'),
       path('eliminar_todo_tierra_cultivo', views.eliminar_todo_tierra_cultivo,name='eliminar_todo_tierra_cultivo'),

       path('gestion_img_galeria_principal', views.gestion_img_galeria_principal, name='gestion_img_galeria_principal'),
       path('configuracion/galeria_imagenes_agregar/', views.galeria_imagenes_agregar, name='galeria_imagenes_agregar'),
       path('configuracion/galeria_imagenes_eliminar/<int:id>/', views.galeria_imagenes_eliminar, name='galeria_imagenes_eliminar'),
       path('configuracion/galeria_imagenes_editar/<int:id>/', views.galeria_imagenes_editar, name='galeria_imagenes_editar'),



]

home/urls.py
from django.urls import path, include 
from django.conf import settings
from django.conf.urls.static import static
from . import views    
urlpatterns = [
    path('', views.index,name='index'),
    path('registracion', views.registrar,name='registrar'),
    path('validacion', views.mailValidador,name='mailValidador'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

huertas/urls.py
from django.urls import path
from django.urls import include, re_path
from . import views
app_name = 'huertas'
urlpatterns= [ 

       path('gestion_huertas', views.gestion_huertas, name = 'gestion_huertas'),
       path('huertas/huerta_agregar/<int:id>/', views.huerta_agregar, name='huerta_agregar'),
       path('huertas/huerta_eliminar/<int:id>/', views.huerta_eliminar,name='huerta_eliminar'),
       path('huertas/huerta_editar/<int:id>/', views.huerta_editar,name='huerta_editar'),
       path('huerta_canteros_mostrar/<int:id>/', views.huerta_canteros_mostrar,name='huerta_canteros_mostrar'),
       
       path('huerta_cultivos_mostrar/<int:id>/', views.huerta_cultivos_mostrar,name='huerta_cultivos_mostrar'),
       path('huertas/huerta_cultivos_agregar/<int:id>/', views.huerta_cultivos_agregar, name='huerta_cultivos_agregar'),
       
       path('cantero_agregar/<int:id>/', views.cantero_agregar, name='cantero_agregar'),
       path('cantero_eliminar/<int:id>/', views.cantero_eliminar),
       path('cantero_editar/<int:id>/', views.cantero_editar),
       path('cantero_mostrar/<int:id>/', views.cantero_mostrar, name='cantero_mostrar'),
       
       path('canteros_listar/', views.canteros_listar, name='canteros_listar'),
       

       path('cantero_cultivos_agregar/<int:id>/', views.cantero_cultivos_agregar, name='cantero_cultivos_agregar'),
       path('cantero_cultivos_eliminar/<int:id>/', views.cantero_cultivos_eliminar),
       path('cantero_cultivos_editar/<int:id>', views.cantero_cultivos_editar),
       path('cantero_cultivos_mostrar/<int:id>/', views.cantero_cultivos_mostrar, name='cantero_cultivos_mostrar'),








]

configuracion/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.
MES = (
        ('ENE', 'Enero'),
        ('FEB', 'Febrero'),
        ('MAR', 'Marzo'),
        ('ABR', 'Abril'),
        ('MAY', 'Mayo'),
        ('JUN', 'Junio'),
        ('JUL', 'Julio'),
        ('AGO', 'Agosto'),
        ('SEP', 'Septiembre'),
        ('OCT', 'Octubre'),
        ('NOV', 'Noviembre'),
        ('DIC', 'Diciembre'),
    )

SEMANA = (
        ('1', 'Primer Semana'),
        ('2', 'Segunda Semana'),
        ('3', 'Tercer Semana'),
        ('4', 'Cuarta Semana'),
    )

class Hortelano(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE )
    apodo = models.CharField(max_length=30, blank=True)
    def __str__(self):
        return self.usuario.first_name+" "+self.usuario.last_name +' '+ self.apodo


class Tierras_Cultivo(models.Model):
    desc_corta = models.CharField(max_length=25, blank=True)
    descripcion = models.CharField(max_length=255, blank=True)

class Riego_Cultivo(models.Model):
    cantidad = models.SmallIntegerField()
    descripcion = models.CharField(max_length=255, blank=True)

class Plagas(models.Model):
    nombre = models.CharField(max_length=50, blank=True)
    descripcion = models.CharField(max_length=255, blank=True)
    tratamiento = models.CharField(max_length=255, blank=True)

class Enfermedades(models.Model):
    AGENTE_CAUSAL = (
        ('HON', 'Hongos'),
        ('BAC', 'Bacterias'),
        ('NEM', 'Nematodos'),
        ('VIR', 'Virus'),
        ('PAR', 'Plantas Parasitas'),
    )
    nombre = models.CharField(max_length=50, blank=True)
    descripcion = models.CharField(max_length=255, blank=True)
    tratamiento = models.CharField(max_length=255, blank=True)
    agente_causal = models.CharField(max_length=3, choices=AGENTE_CAUSAL)
    sintomas = models.CharField(max_length=255, blank=True)

class Perfil(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.CharField(max_length=255, blank=True)
    web = models.URLField(blank=True)

    # Python 3
    def __str__(self): 
        return self.usuario.username

class Luz_Necesaria_Cultivo(models.Model):
    cantidad = models.SmallIntegerField()
    descripcion = models.CharField(max_length=255, blank=True)

class Ph_Suelo(models.Model):
    valores = models.CharField(max_length=50, blank=True)
    descripcion = models.CharField(max_length=255, blank=True)

class Temperaturas_Cultivos(models.Model):
    nombre = models.CharField(max_length=50, blank=True)
    valores = models.CharField(max_length=50, blank=True)
    descripcion = models.CharField(max_length=255, blank=True)

class Cultivos(models.Model):
    TIPOS_SIEMBRA = (
        ('D', 'Directa'),
        ('S', 'Semillero'),
        ('T', 'Directa / Semillero'),
    )
    LUNA =(
        ('C','Cuarto Creciente'),
        ('M','Cuarto Menguante'),
        ('L','Llena'),
        ('N','Nueva'),
    )
    FAMILIA =(
        ('COM','Compuestas'),
        ('CRU','Cruciferas (Brásicas)'),
        ('UMB','Cruciferas'),
        ('SOL','Solanaceas'),
        ('GRA','Gramineas'),
        ('LEG','Leguminosas'),
        ('QUE','Quenopoidaceas'),
        ('ALL','Alliaceas'),
        ('CUC','Cucurbitaceas'),
        ('CON','Convolvulaceas'),
        ('ASP','Asparagaceae'),
    )
    familia = models.CharField(max_length=3, choices=FAMILIA)
    nombre_cientifico = models.CharField(max_length=50, blank=True)
    nombre = models.CharField(max_length=50)
    descripcion = models.CharField(max_length=255, blank=True)
    tierra = models.ForeignKey(Tierras_Cultivo,on_delete=models.CASCADE, null=True, blank=True)
    tipo_siembra = models.CharField(max_length=1, choices=TIPOS_SIEMBRA)
    luna_siembra = models.CharField(max_length=1, choices=LUNA, null=True, blank=True)
    distancia =  models.FloatField(null=True, blank=True)
    luz = models.ForeignKey(Luz_Necesaria_Cultivo,on_delete=models.CASCADE, null=True, blank=True)
    semana_siembra_desde= models.CharField(max_length=1, choices=SEMANA, null=True)
    mes_siembra_desde= models.CharField(max_length=3, choices=MES, null=True)
    mes_siembra_hasta = models.CharField(max_length=3, choices=MES, null=True)
    semana_siembra_hasta = models.CharField(max_length=1, choices=SEMANA, null=True)
    dias_germinacion = models.CharField(max_length=50, null=True, blank=True)
    temperaturas = models.ForeignKey(Temperaturas_Cultivos,on_delete=models.CASCADE, null=True, blank=True)
    ph = models.ForeignKey(Ph_Suelo,on_delete=models.CASCADE, null=True, blank=True)
    imagen = models.ImageField(upload_to='cultivos',blank=True)
    riego = models.ForeignKey(Riego_Cultivo,on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.familia +"-"+ self.nombre



class Variedad_Cultivo(models.Model):
    nombre = models.CharField(max_length=50, blank=True)
    cultivo = models.ForeignKey(Temperaturas_Cultivos,on_delete=models.CASCADE, null=True, blank=True)
    descripcion = models.CharField(max_length=255, blank=True)

class Asociacion_Cultivo(models.Model):
    cultivo = models.ForeignKey(Cultivos,on_delete=models.CASCADE, null=True, blank=True)
    asociacion = models.ForeignKey(Cultivos,on_delete=models.CASCADE, null=True, blank=True,related_name='%(class)s_asociacion')
    beneficiosa = models.BooleanField(max_length=255, blank=True)

class Plagas_Cultivo(models.Model):
    cultivo = models.ForeignKey(Cultivos,on_delete=models.CASCADE, null=True, blank=True)
    plagas =   models.ForeignKey(Plagas,on_delete=models.CASCADE,  null=True, blank=True)

class Enfermedades_Cultivo(models.Model):
    cultivo = models.ForeignKey(Cultivos,on_delete=models.CASCADE, null=True, blank=True)
    enfermedades  = models.ForeignKey(Enfermedades,on_delete=models.CASCADE, null=True, blank=True)

class Galeria(models.Model):
    nombre = models.CharField(max_length=60)
    

class GaleriaImagen(models.Model):
    nombre = models.CharField(max_length=60)
    imagen = models.ImageField(upload_to='galeriaPrincipal',blank=True)
    leyenda = models.CharField(max_length=255,blank=True)
    galeria = models.ForeignKey(Galeria,on_delete=models.CASCADE)

@receiver(post_save, sender=User)
def crear_usuario_perfil(sender, instance, created, **kwargs):
    if created:
        Perfil.objects.create(usuario=instance)

@receiver(post_save, sender=User)
def guardar_usuario_perfil(sender, instance, **kwargs):
    instance.perfil.save()

huertas/models.py
from django.db import models
from configuracion.models import Hortelano, Cultivos
# Create your models here.
class Huerta(models.Model):
    hortelano = models.ForeignKey(Hortelano,on_delete=models.CASCADE)
    nombre = models.CharField(max_length=80)
    coord_x = models.FloatField(blank=True)
    coord_y = models.FloatField(blank=True)
    ancho = models.FloatField(blank=True)
    largo = models.FloatField(blank=True)
    def __str__(self):
        return self.nombre  


class Canteros(models.Model):
    huerta = models.ForeignKey(Huerta,on_delete=models.CASCADE)
    nombre = models.CharField(max_length=80)
    ancho = models.FloatField(blank=True)
    largo = models.FloatField(blank=True)
    ubicacion_x = models.FloatField(blank=True)
    ubicacion_y = models.FloatField(blank=True)
    
    def __str__(self):
        return self.nombre +" "+ self.huerta.nombre

class Cantero_Cultivos(models.Model):
    cantero = models.ForeignKey(Canteros,on_delete=models.CASCADE)
    cultivo = models.ForeignKey(Cultivos,on_delete=models.CASCADE)
    fechaSiembra = models.DateField(blank=True, null=True)
    fechaCosecha = models.DateField(blank=True, null=True)
    cantidad_sembrada = models.SmallIntegerField(blank=True, null=True)
    observaciones = models.CharField(max_length=255, null=True, blank=True)
    
    def __str__(self):
        return self.cantero.nombre +"-"+ self.cultivo.nombre

huertas/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm 
from django.contrib.auth.models import User


from .models import Huerta, Canteros, Cultivos, Cantero_Cultivos 

class HuertaForm(forms.ModelForm):
    class Meta:
        model = Huerta
        fields = '__all__'
        widgets = {
            'hortelano':  forms.Select(attrs = {'option':1} )

        }
    def __init__(self, *args, **kwargs): 
        super(HuertaForm, self).__init__(*args, **kwargs) 
        self.fields['hortelano'].empty_label = None

class CanteroForm(forms.ModelForm):
    class Meta:
        model = Canteros
        fields = '__all__'
        widgets = {
            'huerta': forms.TextInput(attrs={'readonly': 'true'}),
        }
        labels = {
               'nombre': 'Nombre Cantero',
            }
        help_texts = {
               'Nombre': 'Escriba un nombre identificador del Cantero'
            }
        error_messages = {
               'nombre': {
               'max_length': "Nombre solo puede ser de 50 caracteres de largo"
                }
            }
        field_classes = {
      #         'email': EmailCoffeehouseFormField
            },
        localized_fields = '__all__'

    def __init__(self, *args, **kwargs): 
        super(CanteroForm, self).__init__(*args, **kwargs) 
        self.fields['huerta'].empty_label = None
  #      self.fields['huerta'].disabled ='false'


class Cantero_CultivosForm(forms.ModelForm):
    class Meta:
        model = Cantero_Cultivos
        fields = '__all__'

huertas/templates/cultivos_listar.html
{% extends "base_nav.html"%}
{% block title %} List. Huertas {% endblock %}
{% load static %}
{% block style %} 
    <link rel='stylesheet' href="{% static 'css/huertas.css' %}" type="text/css">
    <script type="text/javascript" src="{% static 'js/cultivos.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.1/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
{% endblock %}
 
{% block body %} 
{% load static %}
<div class="row">
    <div class="alertas">
        {% if messages %}
        {% for message in messages %}
        <div>
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <strong class="text-dark">{{ message }}</strong>
        </div>
        {% endfor %}
        {% endif %}
    </div>
    <div class="datos-cuerpo-cabecera">
    </div>
    <div class="datos-cuerpo-listado">
        <h1>Configuracion de Cultivos</h1>
        <div id="container">
            <div class="search">
                <div class="searchbox">
                    <label>Buscar:</label>
                    <span class="info">(Puede ser un nombre, nombre cientifico, descripcion)</span>
                    <input id="search_input" type="text" name="q">
                    {% csrf_token %}
                </div>
                <div class="results">
                    <h1 class="error"></h1>
                    <div class="wrapper"></div>
                </div>
            </div>
        </div>
        <div class="tabla-listar">
            <div class="agregar">
                <a href="{% url 'configuracion:cultivo_agregar'  %}">
                    <img src="{% static 'img/agregar.png' %}" alt="agregar" title="agregar">
                </a>

            </div>

            <table id="resultados" class="table">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Familia </th>
                        <th>Nombre </th>
                        <th>Nom. Cientifico </th>
                        <th>Imagen </th>
                        <th>Variedad </th>
                        <th>Descripcion </th>
                        <th colspan="3">Opciones</th>
                    </tr>
                </thead>
                <tbody id="listCultivos">
                    {% if listadoCultivos %}
                    {% for listadoCultivos in listadoCultivos%}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{listadoCultivos.get_familia_display }}</td>
                        <td>{{listadoCultivos.nombre}}</td>
                        <td>{{listadoCultivos.nombre_cientifico}}</td>
                        <td>
                            {% if listadoCultivos.imagen %}
                            <img  src="{{ listadoCultivos.imagen.url}}" width="70" height="70" >
                            {% endif %}
                        </td>
                        <td>{{listadoCultivos.variedad}}</td>
                        <td>{{listadoCultivos.descripcion}}</td>
                        <td colspan="3"><a href="{% url 'configuracion:cultivo_editar' listadoCultivos.id %}" class=""><img
                                    src="{% static 'img/editar.png' %}" alt="Editar" title="Editar"></a>
                            <a href="{% url 'configuracion:cultivo_eliminar' listadoCultivos.id %}" class=""><img
                                    src="{% static 'img/eliminar.png' %}" alt="Eliminar" title="Eliminar"></a>
                        </tr>
                    {% endfor %}
                    {% endif %}
                </tbody>
            </table>
        </div>
    </div>
</div>
<script>
    $(document).ready(__init);
</script>
{% endblock %}  

huertas/templates/huerta_cultivos_mostrar.html
{% extends "base_nav.html"%}
{% block title %} Mostrar Huerta {% endblock %}
{% load static %}
{% block style %} 
    <link rel='stylesheet' href="{% static 'css/canteros.css' %}" type="text/css">
 {% endblock %}

{% block nav %}
 <div class="hortelano-mostrar">
    <h3>Hortelano : {{ hortelano.nombre }} {{ hortelano.apodo }} mail:{{ hortelano.mail }}</h3>
</div>
<div class="huerta-mostrar">
    <h3>Huerta: {{ huerta.nombre }} Ubicacion: {{ huerta.coordX }} :{{ huerta.coordX  }} Dimensiones: L:{{ huerta.largo  }} A:{{ huerta.ancho  }}</h3>
</div>
{% endblock %}

{% block body %} 
 <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-4 col-xl-4">
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-dismissible alert-success">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <strong class="text-dark">{{ message }}</strong>
            </div>
            {% endfor %}    
        {% endif %}
    </div>
    <div class="col-sm-12 col-md-4 col-lg-8 col-xl-8">
        <h1>Configuracion de Cultivos</h1>
        <div class="agregar">
            <a href="{% url 'huertas:huerta_cultivos_agregar' huerta.id %}">
                <img src="{% static 'img/agregar.png' %}" alt="agregar" title="agregar">
            </a>

        </div>

        <div class="table-responsive ">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Nombre Cultivo</th>
                        <th colspan="3">Opciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for listadoCultivos in listadoCultivos%}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{listadoCultivos.cultivo.nombre}}</td>
                        <td><a href="/huertas/cantero_editar/{{listadoCultivos.id}}/" class="">Editar</a></td>
                        <td><a href="/huertas/cantero_eliminar/{{listadoCultivos.id}}" class="">Eliminar</a></td>
                        <td><a href="/huertas/cantero_mostrar/{{listadoCultivos.id}}/" class="">Mostrar</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock %}  

huertas/templates/huertas_listar.html
{% extends "base_nav.html"%}
{% block title %} List. Huertas {% endblock %}
{% load static %}
{% block style %} 
    <link rel='stylesheet' href="{% static 'css/huertas.css' %}" type="text/css">
 {% endblock %}
 
{% block body %} 
{% load static %}
<div class="row">
    <div class="alertas">
        {% if messages %}
        {% for message in messages %}
        <div>
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <strong class="text-dark">{{ message }}</strong>
        </div>
        {% endfor %}
        {% endif %}
    </div>
    <div class="datos-cuerpo-cabecera">
    </div>
    <div class="datos-cuerpo-listado">
        <h1>Configuracion de Huertas</h1>
        <div class="tabla-listar">
            <div class="agregar">
                <a href="{% url 'huertas:huerta_agregar' hortelano.id %}">
                    <img src="{% static 'img/agregar.png' %}" alt="agregar" title="agregar">
                </a>

            </div>

            <table class="table">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Nombre Huerta</th>
                        <th>Coord. X</th>
                        <th>Coord. Y</th>
                        <th>Ancho</th>
                        <th>Largo</th>
                        <th colspan="3">Opciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% if listadoHuertas %}
                    {% for listadoHuertas in listadoHuertas%}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{listadoHuertas.nombre}}</td>
                        <td>{{listadoHuertas.coord_x}}</td>
                        <td>{{listadoHuertas.coord_y}}</td>
                        <td>{{listadoHuertas.ancho}}</td>
                        <td>{{listadoHuertas.largo}}</td>
                        <td colspan="3"><a href="{% url 'huertas:huerta_editar' listadoHuertas.id %}" class=""><img
                                    src="{% static 'img/editar.png' %}" alt="Editar" title="Editar"></a>
                            <a href="{% url 'huertas:huerta_eliminar' listadoHuertas.id %}" class=""><img
                                    src="{% static 'img/eliminar.png' %}" alt="Eliminar" title="Eliminar"></a>
                            <a href="{% url 'huertas:huerta_canteros_mostrar' listadoHuertas.id %}" class=""><img
                                    src="{% static 'img/mostrar_huerta.png' %}" alt="Mostrar Canteros"
                                    title="Mostrar Canteros"></a>
                            <a href="{% url 'huertas:huerta_cultivos_mostrar' listadoHuertas.id %}" class=""><img
                                        src="{% static 'img/mostrarCultivos.jpg' %}" alt="Mostrar Cultivos"
                                        title="Mostrar Cultivos" height="40" width="40"></a>
                        </tr>
                    {% endfor %}
                    {% endif %}
                </tbody>
            </table>
      
            <p id="message"></p>
            {% for listadoHuertas1 in listadoHuertas %}
            <h3>{{ forloop.counter }}) {{ listadoHuertas1.nombre }}</h3>
            <p>{{ listadoHuertas1.hortelano }} </p>
            <a class="likebutton" id="like{{listadoHuertas1.id}}" href="#" data-catid="{{ listadoHuertas1.id }}">Like</a>
            {% endfor %}
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.1/jquery.min.js"></script>
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.1/jquery-ui.min.js"></script>
            <script type="text/javascript">
            $('.likebutton').click(function(){
            var catid;
            catid = $(this).attr("data-catid");
            $.ajax(
            {
                type:"GET",
                url: "/likepost",
                data:{
                         id: catid
                },
                success: function( data ) 
                {
                    $( '#like'+ catid ).remove();
                    $( '#message' ).text(data);
                }
             })
        });

        </script>

        </div>
    </div>
</div>

{% endblock %}  