RegiHuer/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

composeexample/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
]
urlpatterns += [
    path('catalog/', include('catalog.urls')),
]
urlpatterns += [
    path('', RedirectView.as_view(url='/catalog/', permanent=True)),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

configuracion/urls.py
from django.urls import path
from django.urls import include, re_path
from . import views
app_name = 'configuracion'
urlpatterns= [ 
       path('gestion_hortelanos', views.gestion_hortelanos,name='gestion_hortelanos'),
       path('configuracion/consultaPersona/<int:persona_id>/', views.consultaPersona, name='consultaPersona'),
       path('configuracion/registrarHortelano/', views.registrarHortelano),
       path('hortelano_editar/<int:id>/', views.hortelano_editar, name='hortelano_editar'),
       path('hortelano_modificar/', views.hortelano_modificar),
       path('hortelano_eliminar/<int:id>', views.hortelano_eliminar),

       path('gestion_cultivos', views.gestion_cultivos, name = 'gestion_cultivos'),
       path('cultivo_agregar', views.cultivo_agregar, name='cultivo_agregar'),
       path('cultivo_eliminar/<int:id>', views.cultivo_eliminar, name='cultivo_eliminar'),
       path('cultivo_editar/<int:id>', views.cultivo_editar, name='cultivo_editar'),
       re_path(r'^configuracion/cultivo_buscar', views.cultivo_buscar, name ='cultivo_buscar'),


       path('gestion_tierras_cultivo/', views.gestion_tierras_cultivo, name = 'gestion_tierras_cultivo'),
       path('configuracion/tierras_cultivo_agregar/', views.tierras_cultivo_agregar, name='tierras_cultivo_agregar'),
       path('configuracion/tierras_cultivo_eliminar/<int:id>/', views.tierras_cultivo_eliminar, name='tierras_cultivo_eliminar'),
       path('configuracion/tierras_cultivo_editar/<int:id>/', views.tierras_cultivo_editar, name='tierras_cultivo_editar'),

       path('gestion_temperaturas/', views.gestion_temperaturas, name = 'gestion_temperaturas'),
       path('configuracion/temperaturas_agregar/', views.temperaturas_agregar, name='temperaturas_agregar'),
       path('configuracion/temperaturas_eliminar/<int:id>/', views.temperaturas_eliminar, name='temperaturas_eliminar'),
       path('configuracion/temperaturas_editar/<int:id>/', views.temperaturas_editar, name='temperaturas_editar'),

       path('gestion_luz_cultivos/', views.gestion_luz_cultivos, name = 'gestion_luz_cultivos'),
       path('configuracion/luz_cultivos_agregar/', views.luz_cultivos_agregar, name='luz_cultivos_agregar'),
       path('configuracion/luz_cultivos_eliminar/<int:id>/', views.luz_cultivos_eliminar, name='luz_cultivos_eliminar'),
       path('configuracion/luz_cultivos_editar/<int:id>/', views.luz_cultivos_editar, name='luz_cultivos_editar'),

       path('gestion_riego_cultivos/', views.gestion_riego_cultivos, name = 'gestion_riego_cultivos'),
       path('configuracion/riego_cultivos_agregar/', views.riego_cultivos_agregar, name='riego_cultivos_agregar'),
       path('configuracion/riego_cultivos_eliminar/<int:id>/', views.riego_cultivos_eliminar, name='riego_cultivos_eliminar'),
       path('configuracion/riego_cultivos_editar/<int:id>/', views.riego_cultivos_editar, name='riego_cultivos_editar'),

       path('gestion_enfermedades/', views.gestion_enfermedades, name = 'gestion_enfermedades'),
       path('configuracion/enfermedades_agregar/', views.enfermedades_agregar, name='enfermedades_agregar'),
       path('configuracion/enfermedades_eliminar/<int:id>/', views.enfermedades_eliminar, name='enfermedades_eliminar'),
       path('configuracion/enfermedades_editar/<int:id>/', views.enfermedades_editar, name='enfermedades_editar'),

       path('gestion_plagas/', views.gestion_plagas, name = 'gestion_plagas'),
       path('configuracion/plagas_agregar/', views.plagas_agregar, name='plagas_agregar'),
       path('configuracion/plagas_eliminar/<int:id>/', views.plagas_eliminar, name='plagas_eliminar'),
       path('configuracion/plagas_editar/<int:id>/', views.plagas_editar, name='plagas_editar'),

       path('configuracion_carga_inicial', views.configuracion_carga_inicial,name='configuracion_carga_inicial'),
       path('carga_inicial_tierra_cultivo', views.carga_inicial_tierra_cultivo,name='carga_inicial_tierra_cultivo'),
       path('eliminar_todo_tierra_cultivo', views.eliminar_todo_tierra_cultivo,name='eliminar_todo_tierra_cultivo'),

       path('gestion_img_galeria_principal', views.gestion_img_galeria_principal, name='gestion_img_galeria_principal'),
       path('configuracion/galeria_imagenes_agregar/', views.galeria_imagenes_agregar, name='galeria_imagenes_agregar'),
       path('configuracion/galeria_imagenes_eliminar/<int:id>/', views.galeria_imagenes_eliminar, name='galeria_imagenes_eliminar'),
       path('configuracion/galeria_imagenes_editar/<int:id>/', views.galeria_imagenes_editar, name='galeria_imagenes_editar'),



]

home/urls.py
from django.urls import path, include 
from django.conf import settings
from django.conf.urls.static import static
from . import views    
urlpatterns = [
    path('', views.index,name='index'),
    path('registracion', views.registrar,name='registrar'),
    path('validacion', views.mailValidador,name='mailValidador'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

huertas/urls.py
from django.urls import path
from django.urls import include, re_path
from . import views
app_name = 'huertas'
urlpatterns= [ 

       path('gestion_huertas', views.gestion_huertas, name = 'gestion_huertas'),
       path('huertas/huerta_agregar/<int:id>/', views.huerta_agregar, name='huerta_agregar'),
       path('huertas/huerta_eliminar/<int:id>/', views.huerta_eliminar,name='huerta_eliminar'),
       path('huertas/huerta_editar/<int:id>/', views.huerta_editar,name='huerta_editar'),
       path('huerta_canteros_mostrar/<int:id>/', views.huerta_canteros_mostrar,name='huerta_canteros_mostrar'),
       
       path('huerta_cultivos_mostrar/<int:id>/', views.huerta_cultivos_mostrar,name='huerta_cultivos_mostrar'),
       path('huertas/huerta_cultivos_agregar/<int:id>/', views.huerta_cultivos_agregar, name='huerta_cultivos_agregar'),
       
       path('cantero_agregar/<int:id>/', views.cantero_agregar, name='cantero_agregar'),
       path('cantero_eliminar/<int:id>/', views.cantero_eliminar),
       path('cantero_editar/<int:id>/', views.cantero_editar),
       path('cantero_mostrar/<int:id>/', views.cantero_mostrar, name='cantero_mostrar'),
       
       path('canteros_listar/', views.canteros_listar, name='canteros_listar'),
       

       path('cantero_cultivos_agregar/<int:id>/', views.cantero_cultivos_agregar, name='cantero_cultivos_agregar'),
       path('cantero_cultivos_eliminar/<int:id>/', views.cantero_cultivos_eliminar),
       path('cantero_cultivos_editar/<int:id>', views.cantero_cultivos_editar),
       path('cantero_cultivos_mostrar/<int:id>/', views.cantero_cultivos_mostrar, name='cantero_cultivos_mostrar'),








]

configuracion/views.py
from django.shortcuts import redirect, render
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

from django.http import HttpResponseBadRequest, HttpResponse, JsonResponse
from django.core import serializers

import csv


from .models import Cultivos, Hortelano,  Tierras_Cultivo, Enfermedades, Plagas, GaleriaImagen, Temperaturas_Cultivos, Luz_Necesaria_Cultivo, Riego_Cultivo
from .forms import  CultivosForm, Tierras_CultivoForm, EnfermedadesForm, PlagasForm,GaleriaImagenForm, TemperaturasForm, LuzForm, RiegoForm
from accesibilidad.views import generarMenu

import json
# Create your views here.


@login_required
def gestion_hortelanos(request):
    menu = generarMenu("hola")
    listadoHortelano = Hortelano.objects.filter(usuario=request.user)
    messages.success(request,"¡Hortelanos Listados!")
    contexto ={ 
        "listadoHortelano": listadoHortelano, 
        "menu": menu
    }
    
    return render(request, "configuracionHortelano.html",  contexto)


def consultaPersona(request, persona_id):
    return HttpResponse("Estas mirando la persona: %s." % persona_id )

def registrarHortelano(request):
    apodo =request.POST['txtApodo']
    usuario = User.objects.get(username=request.POST['txtUsuario'])
    
    hortelano = Hortelano.objects.create(
        apodo= apodo,  
        usuario = usuario
    )
    messages.success(request,"¡Hortelano Creado!")
    return redirect('/configuracion/gestion_hortelanos')

def hortelano_eliminar(request,id):
    hortelano = Hortelano.objects.get(id=id)
    hortelano.delete()
    return redirect('/configuracion/gestion_hortelanos')
    
def hortelano_editar(request,id):
     hortelano = Hortelano.objects.get(id=id)
     return render(request, "hortelano_editar.html",{"hortelano":hortelano})

def hortelano_modificar(request):
    id =request.POST['txtId']
    apodo =request.POST['txtApodo']
    hortelano = Hortelano.objects.get(id=id)
    hortelano.apodo= apodo
    hortelano.save()
    return redirect('/configuracion/gestion_hortelanos')


# Create your views here.
def gestion_cultivos(request):
    listadoCultivos = Cultivos.objects.all()
    messages.success(request,"¡Cultivos Listados!")
    menu = generarMenu("hola")

    contexto ={ "listadoCultivos": listadoCultivos,  
               "menu":menu,
    } 
    return render(request, "cultivos_listar.html",  contexto)


def cultivo_agregar(request):
    if request.method == 'POST':
        form= CultivosForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/configuracion/gestion_cultivos')
    else:
        form =CultivosForm()

    contexto ={ 
            "accion":"Agregar", 
            "form": form,
         } 
    return render(request, "cultivo_editar.html", contexto )

def cultivo_editar(request,id):
    cultivo = Cultivos.objects.get(id = id)
    if request.method == 'POST':
        form= CultivosForm(request.POST, request.FILES, instance=cultivo)
        if form.is_valid():
            form.save()
            return redirect('/configuracion/gestion_cultivos')
    else:
            form = CultivosForm( instance=cultivo)
    
    contexto ={ 
            "accion":"Editar", 
            "form": form,
         } 
    return render(request, "cultivo_editar.html",contexto)


def cultivo_eliminar(request,id):
    cultivo = Cultivos.objects.get(id=id)
    cultivo.delete()
    listadoCultivos = Cultivos.objects.all()
    messages.success(request,"¡Huertas Listadas!")
    contexto ={ "listadoCultivos": listadoCultivos,  } 
    return redirect('/configuracion/gestion_cultivos', contexto)



def cultivo_buscar(request):

    # si no es una peticion ajax, devolvemos error 400
    if not request.is_ajax() or request.method != "POST":
        return HttpResponseBadRequest()

    # definimos el termino de busqueda
    q = request.POST['q']

    #verificamos si el termino de busqueda es un documento de identidad
    cultivos = Cultivos.objects.filter(nombre__contains=q)
    # generamos la query
    print(cultivos  )
    cultivo_fields = (
        'id',
        'familia',
        'nombre',
        'nombre_cientifico',
        'descripcion',
        'variedad',
        'imagen'
    )




def gestion_tierras_cultivo(request):
    menu = generarMenu("hola")
    listadoTierrasCultivo = Tierras_Cultivo.objects.all()
    messages.success(request,"¡Cultivos Listados!")
    contexto ={ "listadoTierrasCultivo": listadoTierrasCultivo,  
                "menu": menu
    } 
    return render(request, "tierras_cultivo_listar.html",  contexto)


def tierras_cultivo_agregar(request):
    if request.method == 'POST':
        form= Tierras_CultivoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/configuracion/gestion_tierras_cultivo/')
    else:
        form =Tierras_CultivoForm()

    contexto ={ 
            "accion":"Agregar", 
            "form": form,
         } 
    return render(request, "tierras_cultivo_editar.html", contexto )

def tierras_cultivo_editar(request,id):
    tierras_cultivo = Tierras_Cultivo.objects.get(id = id)
    if request.method == 'POST':
        form= Tierras_CultivoForm(request.POST, instance=tierras_cultivo)
        if form.is_valid():
            form.save()
            return redirect('/configuracion/gestion_tierras_cultivo/')
    else:
            form = Tierras_CultivoForm( instance=tierras_cultivo)
    
    contexto ={ 
            "accion":"Editar", 
            "form": form,
         } 
    return render(request, "tierras_cultivo_editar.html",contexto)


def tierras_cultivo_eliminar(request,id):
    tierras_cultivo = Tierras_Cultivo.objects.get(id = id)
    tierras_cultivo.delete()
    listadoTierrasCultivo = Tierras_Cultivo.objects.all()
    messages.success(request,"¡Tierras de Cultivo Listadas!")
    contexto ={ "listadoCultivos": listadoTierrasCultivo,  
               } 
    return redirect('/configuracion/gestion_tierras_cultivo/',contexto)



def tierras_cultivo_buscar(request):

    # si no es una peticion ajax, devolvemos error 400
    if not request.is_ajax() or request.method != "POST":
        return HttpResponseBadRequest()

    # definimos el termino de busqueda
    q = request.POST['q']

    #verificamos si el termino de busqueda es un documento de identidad
    tierras_cultivo = Tierras_Cultivo.objects.filter(nombre__contains=q)
    # generamos la query

    user_fields = (
        'desc_corta',
        'descripcion'
    )

    # to json!
    data = serializers.serialize('json', tierras_cultivo, fields=user_fields)

    # eso es todo por hoy ^^
    return HttpResponse(data, content_type="application/json") 


def gestion_enfermedades(request):
    menu = generarMenu("hola")
    listadoEnfermedades = Enfermedades.objects.all()
    messages.success(request,"¡Enfermedades Listados!")
    contexto ={ "listadoEnfermedades": listadoEnfermedades,  
                "menu": menu,
    } 
    return render(request, "enfermedades_listar.html",  contexto)


def enfermedades_agregar(request):
    if request.method == 'POST':
        form= EnfermedadesForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/configuracion/gestion_enfermedades/')
    else:
        form =EnfermedadesForm()

    contexto ={ 
            "accion":"Agregar", 
            "form": form,
         } 
    return render(request, "enfermedades_editar.html", contexto )

def enfermedades_editar(request,id):
    enfermedades = Enfermedades.objects.get(id = id)
    if request.method == 'POST':
        form= EnfermedadesForm(request.POST, instance=enfermedades)
        if form.is_valid():
            form.save()
            return redirect('/configuracion/gestion_enfermedades/')
    else:
            form = EnfermedadesForm( instance=enfermedades)
    
    contexto ={ 
            "accion":"Editar", 
            "form": form,
         } 
    return render(request, "enfermedades_editar.html",contexto)


def enfermedades_eliminar(request,id):
    enfermedades = Enfermedades.objects.get(id = id)
    enfermedades.delete()
    listadoEnfermedades = Enfermedades.objects.all()
    messages.success(request,"Enfermedades Listadas!")
    contexto ={ "listadoEnfermedades": listadoEnfermedades,  } 
    return redirect('/configuracion/gestion_enfermedades/',contexto)



def enfermedades_buscar(request):

    # si no es una peticion ajax, devolvemos error 400
    if not request.is_ajax() or request.method != "POST":
        return HttpResponseBadRequest()

    # definimos el termino de busqueda
    q = request.POST['q']

    #verificamos si el termino de busqueda es un documento de identidad
    enfermedades = Enfermedades.objects.filter(nombre__contains=q)
    # generamos la query

    user_fields = (
        'descripcion',
        'tratamiento'
    )

    # to json!
    data = serializers.serialize('json', enfermedades, fields=user_fields)

    # eso es todo por hoy ^^
    return HttpResponse(data, content_type="application/json") 


def gestion_plagas(request):
    menu = generarMenu("hola")
    listadoPlagas = Plagas.objects.all()
    messages.success(request,"¡Plagas Listados!")
    contexto ={ "listadoPlagas": listadoPlagas,  
               "menu": menu,
    } 
    return render(request, "plagas_listar.html",  contexto)


def plagas_agregar(request):
    if request.method == 'POST':
        form= PlagasForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/configuracion/gestion_plagas/')
    else:
        form =PlagasForm()

    contexto ={ 
            "accion":"Agregar", 
            "form": form,
         } 
    return render(request, "plagas_editar.html", contexto )

def plagas_editar(request,id):
    plagas = Plagas.objects.get(id = id)
    if request.method == 'POST':
        form= PlagasForm(request.POST, instance=plagas)
        if form.is_valid():

configuracion/templates/enfermedades_listar.html
{% extends "base_nav.html"%}
{% block title %} List. Enfermedades {% endblock %}
{% load static %}
{% block style %} 
    <link rel='stylesheet' href="{% static 'css/huertas.css' %}" type="text/css">
 {% endblock %}
 
{% block body %} 
{% load static %}
<div class="row">
    <div class="alertas">
        {% if messages %}
        {% for message in messages %}
        <div>
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <strong class="text-dark">{{ message }}</strong>
        </div>
        {% endfor %}
        {% endif %}
    </div>
    <div class="datos-cuerpo-cabecera">
    </div>
    <div class="datos-cuerpo-listado">
        <h1>Configuracion de Enfermedades</h1>
        <div class="tabla-listar">
            <div class="agregar">
                <a href="{% url 'configuracion:enfermedades_agregar' %}">
                    <img src="{% static 'img/agregar.png' %}" alt="agregar" title="agregar">
                </a>

            </div>

            <table class="table">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Nombre</th>
                        <th>Descripcion</th>
                        <th>Agente Causal</th>
                        <th>Sintoma</th>
                        <th>Tratamiento</th>
                        <th colspan="3">Opciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% if listadoEnfermedades %}
                    {% for listadoEnfermedades in listadoEnfermedades%}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{listadoEnfermedades.nombre}}</td>
                        <td>{{listadoEnfermedades.descripcion}}</td>
                        <td>{{listadoEnfermedades.agente_causal}}</td>
                        <td>{{listadoEnfermedades.sintoma}}</td>
                        <td>{{listadoEnfermedades.tratamiento}}</td>
                        <td colspan="3"><a href="{% url 'configuracion:enfermedades_editar' listadoEnfermedades.id %}" class=""><img
                                    src="{% static 'img/editar.png' %}" alt="Editar" title="Editar"></a>
                            <a href="{% url 'configuracion:enfermedades_eliminar' listadoEnfermedades.id %}" class=""><img
                                    src="{% static 'img/eliminar.png' %}" alt="Eliminar" title="Eliminar"></a>
                    </tr>
                    {% endfor %}
                    {% endif %}
                </tbody>
            </table>
            <p id="message"></p>
            {% for listadoEnfermedades1 in listadoEnfermedades %}
            <h3>{{ forloop.counter }}) {{ listadoEnfermedades1.nombre }}</h3>
            <p>{{ listadoEnfermedades1.hortelano }} </p>
            <a class="likebutton" id="like{{listadoEnfermedades1.id}}" href="#" data-catid="{{ listadoEnfermedades1.id }}">Like</a>
            {% endfor %}
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.1/jquery.min.js"></script>
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.1/jquery-ui.min.js"></script>
            <script type="text/javascript">
            $('.likebutton').click(function(){
            var catid;
            catid = $(this).attr("data-catid");
            $.ajax(
            {
                type:"GET",
                url: "/likepost",
                data:{
                         id: catid
                },
                success: function( data ) 
                {
                    $( '#like'+ catid ).remove();
                    $( '#message' ).text(data);
                }
             })
        });

        </script>

        </div>
    </div>
</div>

{% endblock %}  

configuracion/templates/huertas_listar.html
{% extends "baseConfiguracion.html"%}
{% block title %} List. Huertas {% endblock %}
{% load static %}
{% block style %} 
    <link rel='stylesheet' href="{% static 'css/huertas.css' %}" type="text/css">
 {% endblock %}
 
{% block body %} 
{% load static %}
<div class="row">
    <div class="alertas">
        {% if messages %}
        {% for message in messages %}
        <div>
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <strong class="text-dark">{{ message }}</strong>
        </div>
        {% endfor %}
        {% endif %}
    </div>
    <div class="datos-cuerpo-cabecera">
    </div>
    <div class="datos-cuerpo-listado">
        <h1>Configuracion de Huertas</h1>
        <div class="tabla-listar">
            <div class="agregar">
                <a href="{% url 'configuracion:huerta_agregar' hortelano.id %}">
                    <img src="{% static 'img/agregar.png' %}" alt="agregar" title="agregar">
                </a>

            </div>

            <table class="table">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Nombre Huerta</th>
                        <th>Coord. X</th>
                        <th>Coord. Y</th>
                        <th>Ancho</th>
                        <th>Largo</th>
                        <th colspan="3">Opciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% if listadoHuertas %}
                    {% for listadoHuertas in listadoHuertas%}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{listadoHuertas.nombre}}</td>
                        <td>{{listadoHuertas.coord_x}}</td>
                        <td>{{listadoHuertas.coord_y}}</td>
                        <td>{{listadoHuertas.ancho}}</td>
                        <td>{{listadoHuertas.largo}}</td>
                        <td colspan="3"><a href="{% url 'configuracion:huerta_editar' listadoHuertas.id %}" class=""><img
                                    src="{% static 'img/editar.png' %}" alt="Editar" title="Editar"></a>
                            <a href="{% url 'configuracion:huerta_eliminar' listadoHuertas.id %}" class=""><img
                                    src="{% static 'img/eliminar.png' %}" alt="Eliminar" title="Eliminar"></a>
                            <a href="{% url 'configuracion:huerta_canteros_mostrar' listadoHuertas.id %}" class=""><img
                                    src="{% static 'img/mostrar_huerta.png' %}" alt="Mostrar Canteros"
                                    title="Mostrar Canteros"></a>
                            <a href="{% url 'configuracion:huerta_cultivos_mostrar' listadoHuertas.id %}" class=""><img
                                        src="{% static 'img/mostrarCultivos.jpg' %}" alt="Mostrar Cultivos"
                                        title="Mostrar Cultivos" height="40" width="40"></a>
                        </tr>
                    {% endfor %}
                    {% endif %}
                </tbody>
            </table>
      
            <p id="message"></p>
            {% for listadoHuertas1 in listadoHuertas %}
            <h3>{{ forloop.counter }}) {{ listadoHuertas1.nombre }}</h3>
            <p>{{ listadoHuertas1.hortelano }} </p>
            <a class="likebutton" id="like{{listadoHuertas1.id}}" href="#" data-catid="{{ listadoHuertas1.id }}">Like</a>
            {% endfor %}
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.1/jquery.min.js"></script>
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.1/jquery-ui.min.js"></script>
            <script type="text/javascript">
            $('.likebutton').click(function(){
            var catid;
            catid = $(this).attr("data-catid");
            $.ajax(
            {
                type:"GET",
                url: "/likepost",
                data:{
                         id: catid
                },
                success: function( data ) 
                {
                    $( '#like'+ catid ).remove();
                    $( '#message' ).text(data);
                }
             })
        });

        </script>

        </div>
    </div>
</div>

{% endblock %}  

configuracion/templates/luz_cultivo_listar.html
{% extends "base_nav.html"%}
{% block title %} List. Luz Cultivo {% endblock %}
{% load static %}
{% block style %} 
    <link rel='stylesheet' href="{% static 'css/huertas.css' %}" type="text/css">
    <link rel='stylesheet' href="{% static 'css/cultivos.css' %}" type="text/css">
    <script type="text/javascript" src="{% static 'js/cultivos.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.1/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
{% endblock %}
 
{% block body %} 
{% load static %}
<div class="row">
    <div class="alertas">
        {% if messages %}
        {% for message in messages %}
        <div>
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <strong class="text-dark">{{ message }}</strong>
        </div>
        {% endfor %}
        {% endif %}
    </div>
    <div class="datos-cuerpo-cabecera">
    </div>
    <div class="datos-cuerpo-listado">
        <h1>Gestion de Luz necesaria para los cultivos</h1>
        <div id="container">
            <div class="search">
                <div class="searchbox">
                    <label>Buscar:</label>
                    <span class="info">(Puede ser un nombre, nombre cientifico, descripcion)</span>
                    <input id="search_input" type="text" name="q">
                    {% csrf_token %}
                </div>
                <div class="results">
                    <h1 class="error"></h1>
                    <div class="wrapper"></div>
                </div>
            </div>
        </div>
        <div class="tabla-listar">
            <div class="agregar">
                <a href="{% url 'configuracion:luz_cultivos_agregar'  %}">
                    <img src="{% static 'img/agregar.png' %}" alt="agregar" title="agregar">
                </a>

            </div>

            {% if listado %}
            {% for listado in listado%}
                <details open>
                    <summary>
                        {{forloop.counter}} - {{listado.nombre}}
                        <a href="{% url 'configuracion:luz_cultivos_editar' listado.id %}" class=""><img
                            src="{% static 'img/editar.png' %}" alt="Editar" title="Editar"></a>
                        <a href="{% url 'configuracion:luz_cultivos_eliminar' listado.id %}" class=""><img
                            src="{% static 'img/eliminar.png' %}" alt="Eliminar" title="Eliminar"></a>
                    </summary>
                        <div class="descripcion_cultivos">
                            <h2>Horas de Luz necesarias</h2>
                            <span> {{listado.cantidad }} </span>
                            <br><br>
                            <H2>Descripcion</H2>
                            <span>{{listado.descripcion}}</span>
                            <br>
                        </div>  
                    </details>
            {% endfor %}
            {% endif %}
        </div>
    </div>
</div>
<script>
    $(document).ready(__init);
</script>
{% endblock %}  